//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_Step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flow_Step()
        {
            this.Flow_StepRule = new HashSet<Flow_StepRule>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public int Sort { get; set; }
        public string FormId { get; set; }
        public string FlowRule { get; set; }
        public bool IsCustom { get; set; }
        public bool IsAllCheck { get; set; }
        public string Execution { get; set; }
        public bool CompulsoryOver { get; set; }
        public bool IsEditAttr { get; set; }
    
        public virtual Flow_Form Flow_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flow_StepRule> Flow_StepRule { get; set; }
    }
}
