//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_FormContentStepCheck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flow_FormContentStepCheck()
        {
            this.Flow_FormContentStepCheckState = new HashSet<Flow_FormContentStepCheckState>();
        }
    
        public string Id { get; set; }
        public string ContentId { get; set; }
        public string StepId { get; set; }
        public int State { get; set; }
        public bool StateFlag { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsEnd { get; set; }
    
        public virtual Flow_FormContent Flow_FormContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flow_FormContentStepCheckState> Flow_FormContentStepCheckState { get; set; }
    }
}
