//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_FormContentStepCheckState
    {
        public string Id { get; set; }
        public string StepCheckId { get; set; }
        public string UserId { get; set; }
        public int CheckFlag { get; set; }
        public string Reamrk { get; set; }
        public string TheSeal { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Flow_FormContentStepCheck Flow_FormContentStepCheck { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
