//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_FormAttr
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string AttrType { get; set; }
        public string CheckJS { get; set; }
        public string TypeId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string OptionList { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual Flow_Type Flow_Type { get; set; }
    }
}
