//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_StepRule
    {
        public string Id { get; set; }
        public string StepId { get; set; }
        public string AttrId { get; set; }
        public string Operator { get; set; }
        public string Result { get; set; }
        public string NextStep { get; set; }
    
        public virtual Flow_Step Flow_Step { get; set; }
    }
}
