//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Article_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MIS_Article_Category()
        {
            this.MIS_Article = new HashSet<MIS_Article>();
            this.MIS_Article_Category1 = new HashSet<MIS_Article_Category>();
        }
    
        public string Id { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Sort { get; set; }
        public string ImgUrl { get; set; }
        public string BodyContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool Enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MIS_Article> MIS_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MIS_Article_Category> MIS_Article_Category1 { get; set; }
        public virtual MIS_Article_Category MIS_Article_Category2 { get; set; }
    }
}
