//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Article
    {
        public string Id { get; set; }
        public int ChannelId { get; set; }
        public string CategoryId { get; set; }
        public string Title { get; set; }
        public string ImgUrl { get; set; }
        public string BodyContent { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Click { get; set; }
        public int CheckFlag { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> CheckDateTime { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual MIS_Article_Category MIS_Article_Category { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
    }
}
