//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WC_OfficalAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WC_OfficalAccounts()
        {
            this.WC_MessageResponse = new HashSet<WC_MessageResponse>();
        }
    
        public string Id { get; set; }
        public string OfficalId { get; set; }
        public string OfficalName { get; set; }
        public string OfficalCode { get; set; }
        public string OfficalPhoto { get; set; }
        public string OfficalKey { get; set; }
        public string ApiUrl { get; set; }
        public string Token { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public string AccessToken { get; set; }
        public string Remark { get; set; }
        public bool Enable { get; set; }
        public bool IsDefault { get; set; }
        public int Category { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string ModifyBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WC_MessageResponse> WC_MessageResponse { get; set; }
    }
}
